### PR TITLE
Update text9.txt

### PR DESCRIPTION
**Pull request by Jimmy-Nutron**
updated the story. great start

### CODE REVIEW

**Review by syrsqe — COMMENTED** [review]
Maybe It should rhyme a bit better

**Comment by Jimmy-Nutron** [comment]
okay, but will you aprove it anyway

**Review by syrsqe — CHANGES_REQUESTED** [review]
change something

**Review by syrsqe — APPROVED** [review]

**Review by syrsqe — APPROVED** [review]
good job

**Pull request merged**
